import fs from 'node:fs';

/**
 * Posts (or updates) the documentation-freshness report as a PR comment.
 * Invoked from .github/workflows/doc-freshness.yml via actions/github-script.
 */
export default async ({ github, context }) => {
  const report = fs.readFileSync('.doc-freshness-reports/report.md', 'utf8');

  // Find existing comment
  const { data: comments } = await github.rest.issues.listComments({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: context.issue.number,
  });

  const botComment = comments.find((c) => c.user.type === 'Bot' && c.body.includes('Documentation Freshness Report'));

  const body = `## 📚 Documentation Freshness Report\n\n${report}\n\n---\n*Generated by doc-freshness workflow*`;

  if (botComment) {
    await github.rest.issues.updateComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      comment_id: botComment.id,
      body,
    });
  }
  else {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: context.issue.number,
      body,
    });
  }
};
